[package]
name = "frog_quest_battle"
version = "0.1.0"
authors = ["Remi Bernotavicius <remi@abort.cc>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "*"
euclid = "*"
js-sys = "*"
log = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
wasm-logger = "*"

[dependencies.web-sys]
version = "*"
features = [
  "Blob",
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "HtmlCanvasElement",
  "HtmlInputElement",
  "KeyboardEvent",
  "MessageEvent",
  "Performance",
  "RtcDataChannel",
  "RtcDataChannelEvent",
  "RtcIceCandidate",
  "RtcPeerConnection",
  "RtcPeerConnectionIceEvent",
  "RtcSdpType",
  "RtcSessionDescriptionInit",
  "RtcSignalingState",
  "WebGl2RenderingContext",
  "WebGlBuffer",
  "WebGlProgram",
  "WebGlShader",
  "WebGlTexture",
  "WebGlUniformLocation",
  "WebGlVertexArrayObject",
  "Window",
]
